# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Thought' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thought
    pod 'Firebase/Auth'
    pod 'Firebase/Analytics'
    pod 'IQKeyboardManagerSwift'
    pod 'Firebase/Core'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'Firebase/Firestore'


  target 'ThoughtTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThoughtUITests' do
    # Pods for testing
  end

end
